### ISSUE TITLE
HOW DO I TURN OFF?

### ISSUE THREAD

**Issue by Somgonk** [Lakr233/ActivateMac#24]
I downloaded this as a joke and now I don't know how to get rid of it. Please help me.

**Comment by Lakr233** [comment]
you need to kill it via terminal or reboot

**Comment by Lakr233** [comment]
First, run following command in Terminal.app.

```
➜  ~ ps -e | grep Activate.app
24522 ??         0:00.27 /Applications/Activate.app/Contents/MacOS/Activate
```

You see the number 24522 corresponding to the PID of this app. (aka process identifier)

Then you gonna kill it via command.

```
kill 24522
```

That's all.

**Comment by mbs0ft** [comment]
you can exit app easier by typing this in Terminal:

`killall Activate `
